### ISSUE TITLE
“研究生用户，入校登记成功”显示问题

### ISSUE THREAD

**Issue by FranklinDX3906** [szl0834/PingAnChengDian#2]
在1080宽度分辨率的手机上出现“功”字换行显示的情况

**Comment by FranklinDX3906** [comment]
在微信界面和浏览器界面均出现这种情况，然而在其他手机上，就算同是1080分辨率也未出现相同问题，猜测可能是谷歌浏览器渲染等问题

**Comment by FranklinDX3906** [comment]
找到原因了，当手机为1080分辨率，设置中显示大小为默认时，会出现换行的情况，原因是“显示大小”控制的是文字、图片等界面元素的大小，当1080默认显示大小时，该行文字会横向在手机屏幕溢出，所以造成了换行，低于该分辨率的手机应该也有相同问题，需要调整手机系统设置

**Comment by szl0834** [comment]
目前我不太有能力解决这个适配问题

**Comment by FranklinDX3906** [comment]
没事老哥，只是提出的issue罢了，最后还是非常感谢感谢老哥的项目：）

**Comment by szl0834** [comment]
稍微修复了一下，现在换行不会太过突兀了
